language: minimal
sudo: false

addons:
    apt_packages:
    - lib32stdc++6

branches:
  only:
  - travis

env:
  global:
    - secure: "ylAgFobaHj4qEqBEC7Xft8prK8V7XdRgk5jYwUf9VQJ6bak52bdPOumiMij6pF3CKLDR0AIzmqakD7CPPBE/ySGY4CQk0WOn5tGs2J0b0yVk6TLltHrOtKcZD6RLrWq7tUtznKEumcKxAeklDLyqHhVw3d7YGWYFeFrN8dt+yvJuxTdP0MGjmDQQfMSIuKQN7ANOWUIs033Zr5sQBqjm3YcB3Hahb3xgG2YzR/FTXSMwPBnlmm8nAgUcmGuDc6DKlyqntiN+D6WXJItFs/Yagid6nN89RuWSdYio6EAQVCRE5PlfikIXf3XV//vnKVR1DS145c/RfRNTT/2WO+6LKuWQ1m4QQ80eStlGTIo/SAUu9YtGIHFPe3JMFfIu4xCkfCSVX6uczwgEUMx2Zb1InmB/5dE7XM8CFqkLSXb3wYRqaFvuu72N0h3/DE3uX4WmhYFF4ykhUDlxkBLnkQF47DMKKHgfD3HrxLlA7yNvF5i4GeDxh5mhD3fvqwYGsAKtWFvjsQDHxJzrxTzkHL+y8fMdoctf8FLeSosH7fZDOxKd2HigSy7iJ21hjvgCXWZlm+eoiEEPCG2S0tykWVdulAj2HegX53fzDWhF8E2jazO6qEihCUQmNx+6GEpVf5cM2HTZqi5hohcwG+Cq6mHrE5K9Rc71MilW14ITJjyrue8="
    - secure: "HjGqrUXRFx9oCcia1iXJ6Yt59CcqHEg77MEshMzReWCmVD/ED+575855qii01+5rnVG8L2Q/vX5VDW+jHo/WLv2CZTbPqR86VwZF79mfN4ifk6Eizhbs8280Z6IpWEbB8J5gAPtz2M3hbTR+Dfp8oHmD2A+un2aJYt4qdBCCzHEcrwgaYrS8i1tvOLwW3se3+em2TTWmXMDIXb65B292Ce8R8fQRuNiLKP4IwdJRAzNLitLPqAXWYuEDHvEtWPGHgBlJGOqxtH+nFUgU/jS9Y1HPVMAWbV7Gc/5AomD7PqAZEcEbh3Py4rrpuV6YPQmYRfBA8ELMZ4JogxGH+Ge12q3LYaD7xNr5WbiX5h1qHl5zpw0YWy543Y/nNsWwhUKTiOBPonYCt7sHI19hhZoJQdAf1oJH2J6OB8+iDQQFiLS6ThmJG8NpFZtdE5nDcrnrLRSDFDvwGDwd1N2PGTj9MFx092BjUzRE6KA8wEysPuvUTzIWbPcfAf4GTyg1IiY7VYHleQHW2U/L1XH6LCHoFhJwrnbleVeFyqPIHhwAdehrEy8xNRyLaWe4kfPWNlDgKisvBdNOULBG5eFTDNbMttNtX3kZMecqb4E+sGx2vMibNJKj0oubwmS1sJ1VwM+/VjoxIGFWsvAG0aup8fRkMAnQ0qmNBJ6/4+WmJ+GJoI0="

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^travis|dev|master$


before_script:
  # SM
  - wget "https://sourcemod.net/latest.php?os=linux&version=1.9" -O /tmp/sourcemod.tar.gz
  - mkdir ~/sm && cd ~/sm
  - tar xzf /tmp/sourcemod.tar.gz addons/sourcemod/scripting
  - PATH+=:$PWD/addons/sourcemod/scripting
  # SM Builder
  - git clone "https://github.com/splewis/sm-builder" ~/sm-builder
  - cd ~/sm-builder
  - pip install --user -r requirements.txt
  - python setup.py install --prefix=~/.local

  - cd $TRAVIS_BUILD_DIR

script:
  - smbuilder --flags " -i=addons/sourcemod/scripting/include"
