language: minimal
sudo: false

addons:
    apt_packages:
    - lib32stdc++6

branches:
  only:
  - travis

env:
  global:
    - secure: "ylAgFobaHj4qEqBEC7Xft8prK8V7XdRgk5jYwUf9VQJ6bak52bdPOumiMij6pF3CKLDR0AIzmqakD7CPPBE/ySGY4CQk0WOn5tGs2J0b0yVk6TLltHrOtKcZD6RLrWq7tUtznKEumcKxAeklDLyqHhVw3d7YGWYFeFrN8dt+yvJuxTdP0MGjmDQQfMSIuKQN7ANOWUIs033Zr5sQBqjm3YcB3Hahb3xgG2YzR/FTXSMwPBnlmm8nAgUcmGuDc6DKlyqntiN+D6WXJItFs/Yagid6nN89RuWSdYio6EAQVCRE5PlfikIXf3XV//vnKVR1DS145c/RfRNTT/2WO+6LKuWQ1m4QQ80eStlGTIo/SAUu9YtGIHFPe3JMFfIu4xCkfCSVX6uczwgEUMx2Zb1InmB/5dE7XM8CFqkLSXb3wYRqaFvuu72N0h3/DE3uX4WmhYFF4ykhUDlxkBLnkQF47DMKKHgfD3HrxLlA7yNvF5i4GeDxh5mhD3fvqwYGsAKtWFvjsQDHxJzrxTzkHL+y8fMdoctf8FLeSosH7fZDOxKd2HigSy7iJ21hjvgCXWZlm+eoiEEPCG2S0tykWVdulAj2HegX53fzDWhF8E2jazO6qEihCUQmNx+6GEpVf5cM2HTZqi5hohcwG+Cq6mHrE5K9Rc71MilW14ITJjyrue8="
    - secure: "EoinZd17cDK66nvQ/nCwy2pUbH9dhxtSXWP6SfoXRAMWLxUtGLNDz9qczxjZryNui3I7xH91UmuwA0xnU4yaLPGJkCwg6bhKpMFis3EUI/EdkW3Qf1bj50JqDIqcJQ2TA2on2ohTduFGVBPUfCwAGlsyXZDXE9o0SF3ok5WoVBm/61h6nxK5WmHY5/LUybDUYB1p+y1digM/vSxXRed+52dtBA4A9sYwfjolm26/REst2X8IvHAp4psDf1POhWKf74E8xiKzSjK+3xBZynbiJZLjz/4H/5f7nqUZBvfsE5g/P9wHoQSj4SeFySIGoscmw04M07U9QuX8mVsPlbQXqF6xWhfS/2YkmTLOQS96WFcUS4Iol3zbimU/3+VGfTOmDZrehjvkpmLTQGZkhOxVclRxyqFNcbgFNuhkZqNV58j/hzX8slPN5sPEKI/haV9//iyR/OgMXXTJA1GobE1iPUXzHKsi/kuDZyZiPalO36Z1DC7BS1AhG3JWTNolR6Nvy2LoXdDpgN8tOB1qjhNK4zlCiJLG2Q0Ya8hPAKklh+M2ZYvqySVWISJ6Ey9OgcPA9TN5S7emAqrJuUCpCaedQEsa+vdYtn/lRRIOlGGXDqRtTvLnGuY24ZP0imElj3SC/HwOtXEwIf6TXgcgSR1ax0183PtUNL9hkTT1IQvR2Iw="

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^travis|dev|master$


before_script:
  # SM
  - wget "https://sourcemod.net/latest.php?os=linux&version=1.9" -O /tmp/sourcemod.tar.gz
  - mkdir ~/sm && cd ~/sm
  - tar xzf /tmp/sourcemod.tar.gz addons/sourcemod/scripting
  - PATH+=:$PWD/addons/sourcemod/scripting
  # SM Builder
  - git clone "https://github.com/splewis/sm-builder" ~/sm-builder
  - cd ~/sm-builder
  - pip install --user -r requirements.txt
  - python setup.py install --prefix=~/.local

  - cd $TRAVIS_BUILD_DIR

script:
  - smbuilder --flags " -i=addons/sourcemod/scripting/include"
